// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The reply to an EchoRequest, carrying the same request_id. Bidirectional.
 * See `EchoRequest` for the 53-bit constraint on request_id.
 */
export type EchoResponse = { request_id: number, payload: Array<number>, };
