// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A request to echo a payload back. Establishes request_id correlation
 * (ADR 0022 Q6). Bidirectional.
 */
export type EchoRequest = { request_id: number, payload: Array<number>, };
