// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Core's acceptance of the host's Handshake. Core -> Host. ADR 0022 Q4b.
 * Unit variant in the Message enum (no fields).
 */
export type HandshakeAck = null;
