// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The host's first frame. Host -> Core. ADR 0022 Q3.
 */
export type Handshake = { protocol_version: number, host_pid: number, };
