// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Core probes liveness. Core -> Host. ADR 0022 Q7.
 * Unit variant in the Message enum (no fields).
 */
export type Heartbeat = null;
