// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolErrorCode } from "./ProtocolErrorCode";

/**
 * Every Host Protocol message. ADR 0022 Q5: the wire envelope is a map
 * with a `"type"` field set to the verbatim PascalCase variant name, and the
 * variant's fields flattened alongside it (e.g. {"type":"Handshake",
 * "protocol_version":1, "host_pid":123}, {"type":"Heartbeat"}).
 *
 * Implemented manually rather than via `#[serde(tag = "type")]` because
 * rmp-serde does not honor serde's internally-tagged enum representation
 * (3Hren/msgpack-rust issues #130, #153, #250, #327, #225). The inner structs
 * keep their derives for ts-rs codegen; only the enum's serde impl is manual.
 * `#[ts(tag = "type")]` is the ts-rs-native hint (independent of serde) that
 * emits the discriminated-union TS shape matching the wire.
 */
export type Message = { "type": "Handshake", protocol_version: number, host_pid: number, } | { "type": "HandshakeAck" } | { "type": "Heartbeat" } | { "type": "Pong" } | { "type": "Shutdown", drain: boolean, } | { "type": "ShutdownAck" } | { "type": "EchoRequest", request_id: number, payload: Array<number>, } | { "type": "EchoResponse", request_id: number, payload: Array<number>, } | { "type": "ProtocolError", code: ProtocolErrorCode, message: string, };
