// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trivial round-trippable type proving the ts-rs codegen pipeline end-to-end.
 * Real protocol messages arrive in step 2 (grill) and step 3.
 */
export type Ping = { id: number, };
