// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host replies to a Heartbeat. Host -> Core. ADR 0022 Q7.
 * Unit variant in the Message enum (no fields).
 */
export type Pong = null;
