// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolErrorCode } from "./ProtocolErrorCode.ts";

/**
 * A transport-level error. Bidirectional. ADR 0022 Q9.
 */
export type ProtocolError = { code: ProtocolErrorCode, message: string, };
