// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport-level error codes. ADR 0022 Q9: transport-only. ADR 0009
 * in-flight-tool errors are Phase 3 ToolResult variants, never this.
 */
export type ProtocolErrorCode = "UnknownMessageType" | "MalformedFrame" | "UnexpectedMessage" | "HandshakeRejected";
