// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Core tells the host to shut down. Core -> Host. ADR 0022 Q8.
 * drain=true: finish in-flight protocol-message handling, send ShutdownAck, exit.
 * drain=false: exit immediately, no ack.
 */
export type Shutdown = { drain: boolean, };
