// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Host acknowledges a graceful Shutdown (drain=true only). Host -> Core. ADR 0022 Q8.
 * Unit variant in the Message enum (no fields).
 */
export type ShutdownAck = null;
